config/routes.rb
Rails.application.routes.draw do
  root :to => "user_color_board#index"
  post '/user_color_board/update_user_grid_color'
  get '/user_color_board/frequent_grid_updatation'
  get '/user_color_board/leader_board'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
    has_many :user_colors, dependent: :destroy
    validates_presence_of :name, :uniq_identifier

    def self.set_user(ipaddress)
      user = User.find_by(uniq_identifier: ipaddress)
      return user if user
      user_name = "RandomUser_#{SecureRandom.hex(10)}"
      User.create(name: user_name, uniq_identifier: ipaddress)
    end

    def self.users_colors_data
      User.joins(:user_colors).select("users.name as user_name, count(user_colors.id) most_color").group("users.name")
    end

  def user_favourite_color
    self.user_colors.group(:color_code).count.sort_by {|key,value| value}.last[0]
  end

end

app/models/user_color.rb
class UserColor < ApplicationRecord
  belongs_to :user

  validates_presence_of :color_code,:row,:col, :user_id

  def self.update_user_colors(user, data)
  	row, column = data[:grid_postion].split("-")[1].split("_")
  	user.user_colors.create(color_code: data[:color_code], row: row,col: column)
  end

  def self.get_existing_color_code_data(row, col, color_data)
    user_color = color_data[[row, col]].try(:last)
    return [] if user_color.blank?
    [user_color.color_code,"#{user_color.user.name} #{user_color.time_format}"]
	end

	def time_format
    self.updated_at.strftime("%d-%m-%Y %H:%M:%S")
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/user_color_board_controller.rb
class UserColorBoardController < ApplicationController
  before_action :set_user
  before_action :user_color_data, only: [:index, :frequent_grid_updatation]

  def index
  end

  def update_user_grid_color
  	UserColor.update_user_colors(@user, user_params)
    respond_to :js
  end

  def frequent_grid_updatation
  	respond_to :js
  end

  def leader_board
  	@users_data = User.users_colors_data
  end

  private

  def set_user
  	@user = User.set_user(request.remote_ip)
  end

  def user_color_data
  	@user_color ||= UserColor.includes(:user).group_by{|data| [data.row, data.col]}
  end

  def user_params
    params.require(:user_color).permit(:grid_postion, :color_code)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	
	def generate_grid(row,col)
    color_data = fetch_color_info(row, col)
    raw("<div class='content' onclick='update_grid_color(this);'
         id='grid-#{row}_#{col}' style= 'background-color: #{color_data[0]}' title='#{color_data[1]}'></div>")
  end

  def fetch_color_info(row, col)
  	UserColor.get_existing_color_code_data(row, col, @user_color)
  end

end

app/helpers/leader_board_helper.rb
module LeaderBoardHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UserColorPalette</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all'%>
    <%= javascript_include_tag 'application'%>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/user_color_board/_grids.html.erb
<table>
  <%for row in 1..20 do %>
   <tr>
    <% for col in 1..20 do%>
      <td><%= generate_grid(row,col)%></td>
    <%end%>
   </tr>
  <%end%>
</table>

app/views/user_color_board/_header.html.erb
<div class='header'>
	<div class='user'>
		<b>Welcome <%= @user.name%></b>
	</div>

	<div class='navigation'>
		<%= link_to "Leaderboard",user_color_board_leader_board_path, :class=>"#{leader_board}"%>
	</div>
</div>

app/views/user_color_board/frequent_grid_updatation.js.erb
$('#grids').html("<%= escape_javascript render(:partial => 'grids') %>");

app/views/user_color_board/index.html.erb
<%= render partial: "header", locals: {leader_board: ''}%>

<div class='data_content'>

	<div id='color_picker'>
		Color Picker: <br/><input class="colors">
	</div>

	<div id="grids">
	  <%= render partial: "grids"%>
	</div>
</div>

app/views/user_color_board/leader_board.html.erb
<%= render partial: "header", locals: {leader_board: 'active'}%>
<table border='1'>
  <thead>
   <tr>
    <td>S.No</td>
    <td>Username</td>
    <td>Colors Placed</td>
    <td>Favourite Color</td>
   </tr>
  </thead>
  <tbody>
   <%@users_data.each_with_index do |user,index|%>
    <tr>
     <td><%= index+=1%>.</td>
     <td><%= user.name%></td>
     <td><%= user.most_color%></td>
     <td style="background-color: <%= user.user_favourite_color%>"></td>
    </tr>
   <%end%>
  </tbody>
</table>